import { useRef } from 'react';
import { useStore } from '../store';

interface Props {
  onSend: (text: string) => void;
}

export function Composer({ onSend }: Props) {
  const { state } = useStore();
  const ref = useRef<HTMLTextAreaElement>(null);

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const text = ref.current?.value.trim() || '';
    if (!text || state.busy) return;
    if (ref.current) ref.current.value = '';
    onSend(text);
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
      e.preventDefault();
      const text = ref.current?.value.trim() || '';
      if (!text || state.busy) return;
      if (ref.current) ref.current.value = '';
      onSend(text);
    }
  }

  return (
    <form className="composer" onSubmit={handleSubmit}>
      <textarea
        ref={ref}
        rows={4}
        placeholder="Write the next scene, ask for a continuation, or give direction..."
        onKeyDown={handleKeyDown}
      />
      <div className="composer-footer">
        <div className="hint">Saved locally. Recalled with NervaPack. Generated by your local model server.</div>
        <button className="primary" type="submit" disabled={state.busy}>
          {state.busy ? 'Generating…' : 'Generate'}
        </button>
      </div>
    </form>
  );
}
